# Generated by Django 3.0.8 on 2020-07-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('categorie', models.CharField(max_length=100)),
                ('tarif_intra', models.IntegerField()),
                ('tarif_extra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.IntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('intra_extra', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('naissance', models.DateTimeField()),
                ('licence', models.IntegerField()),
                ('genre', models.CharField(max_length=1)),
                ('taille', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
